name: Test certifi-linux

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.11", "3.12"]
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install hatch
        run: python -m pip install hatch
      - name: Test
        run: hatch run all:test
      - name: Display Found Cert Path
        run: hatch run python${{ matrix.python-version }} scripts/print_cert_path.py
